# _config.yml

# required, replace with your own information -----
title: Derek Rollend
author: Derek Rollend
description: > 
  A website for Derek Rollend
baseurl: "derekrollend.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

